### ISSUE TITLE
Create technology section

### ISSUE THREAD

**Issue by karenmscg** [lecode-dev/lecode-websiteV2#4]
**Contexto**

Criação do componente onde as habilidades do time da leCode são mostradas. O componente deve conter imagens e textos, dispostos em colunas onde cada especialidade é mostrada.

**Desenvolvimento**

- Use o componente `Image` do NextJS para a imagem do background. Use o atributo `fill`. A imagem deve cobrir todo o componente. Se necessário, adicione classes ao componente de estilo
- Os componentes de estilização devem ter nomes descritivos exemplo `<TechnologyContainer/>`
- O arquivo de estilização precisa utilizar um HTML descritivo para a criação de componentes de estilo, evite usar `div` para todos os componentes
- Os arquivos de imagem devem conter a propriedade alt com um texto curto e/ou com palavras chaves
-  No componente pai adicione uma ID para a melhor navegação junto com  a navbar
 
**Versão mobile**

- Na versão mobile os itens são dispostos em forma de coluna. Caso esteja usando `display: flex`, adicione `flex-direction: column`
-  Ajuste o ` height` do componente pai para ` height: fit-content` assim a imagem ainda cobrirá todo o componente. 

**Links uteis**

- Anatomia da section : https://www.figma.com/design/79pZIUrSFKd65HwBEyu6pd/lecode-site?node-id=59-2445&t=6gZPnwdPdkf08gzZ-4
- Anatomia coluna de especialidade : https://www.figma.com/design/79pZIUrSFKd65HwBEyu6pd/lecode-site?node-id=59-2450&t=6gZPnwdPdkf08gzZ-4

**Roteiro de testes**

-  No modo desktop as colunas de especialidades devem estar dispostas em linha horizontal, na versão mobile,  a direção da linha deve ser vertical'

**Comment by DanteBorges** [comment]
Cartão iniciado
